baseURL = "https://alex.mancevice.dev/"
languageCode = "en-us"
title = "Alexander Mancevice"
theme = "hello-friend-ng"

[author]
  name = "small weird number"

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  # dateformNum     = "2006-01-02"
  dateformNumTime = "January 2, 2006"
  description     = "Alexander Mancevice's thoughts & feelings"
  homeSubtitle    = "Senior Software Engineer"

  [params.logo]
    logoText           = "cd ~" # "^,>"
    logoHomeLink       = "/"
    logoCursorDisabled = false
    logoCursorColor    = "#33FF99"
    logoCursorAnimate  = "1s"

  [params.portrait]
    path     = "/images/portrait.png"
    alt      = "Portrait"
    maxWidth = "192px"

  # Social icons
  [[params.social]]
    name = "docker"
    url  = "https://hub.docker.com/u/amancevice"
  [[params.social]]
    name = "github2"
    url  = "https://github.com/amancevice"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/amancevice"
  [[params.social]]
    name = "terraform"
    url  = "https://registry.terraform.io/namespaces/amancevice"
  # [[params.social]]
  #   name = "twitter"
  #   url  = "https://twitter.com/smallweirdnumbr"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts"
  [[menu.main]]
    identifier = "work"
    name       = "Work"
    url        = "work"
